Listen mode
Stebalien/go-p2pcat pull request #2
Opened 2018-11-04 15:19 UTC by magik6k

Just a quick hack, probably can be improved in some ways, but it works for me

2018-11-04 15:21 UTC, magik6k commented on main.go
> +const bufSize = 1 << 20
Need this for some reason, makes transfer about 100x faster (~200mbit vs 2)

2018-11-16 18:04 UTC, Stebalien requested changes
Nice!

2018-11-16 18:04 UTC, Stebalien commented on main.go
> +	for range BootstrapAddresses {
What? I never new this was valid! Awesome!

2018-11-16 18:04 UTC, Stebalien commented on main.go
> +		fmt.Fprintln(flags.Output(), "Usage: p2pcat [-v] [-routed] -listen/MULTIADDR PROTOCOL")
Nit:
```suggestion
		fmt.Fprintln(flags.Output(), "Usage: p2pcat [-v] [-routed] MULTIADDR PROTOCOL")
		fmt.Fprintln(flags.Output(), "  or:  p2pcat [-v] [-routed] -listen PROTOCOL")
```

(at least that's what some GNU commands do in cases like this)

2018-11-16 18:04 UTC, Stebalien commented on main.go
> +		go dhtclient.Provide(ctx, cid.NewCidV1(cid.Raw, mhid), true)
Shouldn't we just call `dht.Bootstrap(ctx)`?

2018-11-16 18:04 UTC, Stebalien commented on main.go
> +		dhtclient, err := dht.New(ctx, node, dhtopt.Client(false))
We should still be a DHT client. We don't really want to *answer* DHT queries.

2018-11-21 01:43 UTC, magik6k commented
(done)

2018-11-27 00:07 UTC, Stebalien approved these changes

2018-11-27 00:07 UTC, merged

2018-11-27 00:07 UTC, Stebalien commented
Awesome! Thanks!